import os
from typing import List, Dict, Any
from effortless_mcp.services.markdown import write_markdown_frontmatter

# Bannière insérée en tête des fichiers Markdown générés : ils sont rendus depuis la
# base JSON (.effortless/) à chaque mutation. Toute édition manuelle serait écrasée.
GENERATED_BANNER = (
    "> ⚠️ **Auto-generated by Effortless** — do not edit manually.\n"
    "> The source of truth is the `.effortless/` database. Any changes here will be overwritten.\n\n"
)


def _cell(value: Any) -> str:
    """Neutralise un texte libre pour une cellule de tableau Markdown : échappe les
    pipes et aplatit les sauts de ligne, qui casseraient sinon la table."""
    text = "" if value is None else str(value)
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()


def _inline(value: Any) -> str:
    """Aplatit les sauts de ligne pour une interpolation inline (titres, etc.)."""
    text = "" if value is None else str(value)
    return text.replace("\r", " ").replace("\n", " ").strip()

def sync_decisions_to_markdown(
    markdown_path: str,
    phase_id: str,
    decisions: List[Dict[str, Any]]
) -> None:
    """
    Génère le fichier Markdown du registre de décisions à partir du tableau JSON.
    """
    content = "# 🗃️ Decision Register (ADR)\n\n"
    content += GENERATED_BANNER
    content += "This document summarises the design and architecture decisions that have been made.\n\n"
    content += "---\n\n## 🏛️ Decision List\n\n"

    if not decisions:
        content += "*No decisions recorded yet.*\n"
    else:
        for idx, dec in enumerate(decisions, 1):
            content += f"### {idx}. `{dec['id']}` : {_inline(dec['title'])}\n"
            content += f"* **Status** : {dec.get('status', 'Accepted')}\n"
            content += f"* **Date** : {dec.get('date', '')}\n"
            content += f"* **Phase** : {dec.get('phase', '')}\n"
            content += f"* **Context** : {dec.get('context', '')}\n"
            content += f"* **Decision** : {dec.get('decision', '')}\n"

            consequences = dec.get("consequences", [])
            if consequences:
                content += "* **Consequences** :\n"
                for cons in consequences:
                    content += f"  - {cons}\n"

            rejected = dec.get("rejected_alternatives", [])
            if rejected:
                content += "* **Rejected Alternatives** :\n"
                for rej in rejected:
                    content += f"  - {rej}\n"

            content += "\n---\n\n"

    metadata = {
        "phase": phase_id,
        "statut": "Active"
    }

    write_markdown_frontmatter(markdown_path, metadata, content)

def sync_questions_to_markdown(
    markdown_path: str,
    phase_id: str,
    project_name: str,
    questions: List[Dict[str, Any]]
) -> None:
    """
    Génère le fichier Markdown BQO à partir du tableau JSON.
    """
    # Titre principal et métadonnées
    statut_global = "Resolved" if all(q.get("status") == "Resolved" for q in questions) and questions else "Pending"
    if not questions:
        statut_global = "Resolved"  # Pas de question = résolu par défaut

    content = f"# ❓ BQO -- Phase {phase_id} -- {project_name}\n\n"
    content += GENERATED_BANNER
    content += f"**Project** : {project_name}  \n"
    content += f"**Phase** : {phase_id}  \n"
    content += f"**Status** : {statut_global}  \n\n"
    content += "This document lists the open questions for the project.\n\n"
    content += "---\n\n## 📋 Summary Table\n\n"

    # Tableau
    content += "| # | Question | Impact | Status | Confidence | Answer |\n"
    content += "|---|----------|--------|--------|------------|--------|\n"

    if not questions:
        content += "| - | No open questions | - | - | - | - |\n\n"
    else:
        for q in questions:
            statut_fr = "Resolved" if q.get("status") == "Resolved" else "Pending"
            answer_summary = q.get("answer") or ""
            if len(answer_summary) > 30:
                answer_summary = answer_summary[:27] + "..."
            content += f"| {q['id']} | {_cell(q['question'])} | {_cell(q.get('impact', 'Structuring'))} | {statut_fr} | Average | {_cell(answer_summary) or '-'} |\n"
        content += "\n"

    content += "---\n\n## 💬 Question Details\n\n"

    if not questions:
        content += "*No questions recorded.*\n"
    else:
        for q in questions:
            statut_fr = "Resolved" if q.get("status") == "Resolved" else "Pending"
            content += f"### {q['id']} : {_inline(q['question'])}\n"
            content += f"* **Context** : {q.get('context', '')}\n"
            content += f"* **Impact** : **{q.get('impact', 'Structuring')}**\n"

            if q.get("suggestion"):
                content += f"* **LLM Suggestion** : {q.get('suggestion')}\n"

            content += f"* **Status** : {statut_fr}\n"

            if q.get("answer"):
                content += f"* **User Answer** : {q.get('answer')}\n"
                content += f"* **Date Resolved** : {q.get('date_resolved', '')}\n"
            else:
                content += "* **User Answer** : \n"
                content += "* **Date Resolved** : \n"

            content += "\n---\n\n"

    metadata = {
        "phase": phase_id,
        "statut": statut_global
    }

    write_markdown_frontmatter(markdown_path, metadata, content)
